import { Product } from './types';

export const LUXURY_PRODUCTS: Product[] = [
  {
    id: 'prod_1',
    nameEn: 'FIFTY THREE Sterling Royal Band (925 Silver)',
    nameAr: 'خاتم ملكي فضة إيطالية ٩٢٥ (سلسلة ٥٣)',
    priceAED: 1850,
    image: 'https://images.unsplash.com/photo-1599643478518-a784e5dc4c8f?auto=format&fit=crop&q=80&w=600',
    categoryEn: '925 Italian Silver & Non-Tarnish Jewelry',
    categoryAr: 'فضة إيطالية ٩٢٥ ومجوهرات راقية',
    descriptionEn: 'An exquisite 925 Italian sterling silver band from our elite silver collection, featuring custom non-tarnish rhodium shielding for lasting royal luster.',
    descriptionAr: 'خاتم أنيق من الفضة الإيطالية الاسترليني عيار ٩٢٥ من مجموعة الفضة الفاخرة، مع حماية بلاتينية مقاومة لتغير اللون لبريق دائم.',
    stockStatus: 'In Stock',
    stockStatusAr: 'متوفر',
    isPremium: true,
    stock: 15
  },
  {
    id: 'prod_2',
    nameEn: 'Sovereign Italian Silver Neck-Chain',
    nameAr: 'قلادة فضة إيطالية ٩٢٥ سيادية',
    priceAED: 2400,
    image: 'https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?auto=format&fit=crop&q=80&w=600',
    categoryEn: '925 Italian Silver & Non-Tarnish Jewelry',
    categoryAr: 'فضة إيطالية ٩٢٥ ومجوهرات راقية',
    descriptionEn: 'Finely-spaced 925 Italian silver link chain, carefully layered with protective platinum. Guaranteed non-tarnish and brilliant in any climate.',
    descriptionAr: 'سلسلة من الفضة الإيطالية عيار ٩٢٥ منسوجة بدقة فائقة مع طبقة حماية بلاتينية. مقاومة تماماً للبهتان وتغير اللون.',
    stockStatus: 'Low Stock',
    stockStatusAr: 'كمية محدودة',
    isPremium: true,
    stock: 3
  },
  {
    id: 'prod_3',
    nameEn: 'Styles & Grace Signature Oud Intense',
    nameAr: 'عطر ستايلز آند جريس عود إنتنس الحصري',
    priceAED: 1250,
    image: 'https://images.unsplash.com/photo-1541643600914-78b084683601?auto=format&fit=crop&q=80&w=600',
    categoryEn: 'Luxury Perfumes & Watches',
    categoryAr: 'عطور وساعات فاخرة',
    descriptionEn: 'Bespoke combination of intense raw Cambodian agarwood, Damascene rose nectar, and deep leather notes. Encased in a beautiful custom crystal bottle.',
    descriptionAr: 'تركيبة عطرية مخصصة تجمع بين دهن العود الكمبودي الفاخر، بتلات الورد الدمشقي، والجلود الدافئة، معبأة في زجاجة كريستالية رائعة.',
    stockStatus: 'In Stock',
    stockStatusAr: 'متوفر',
    isPremium: false,
    stock: 20
  },
  {
    id: 'prod_4',
    nameEn: 'Grace Elite Chronograph Steel Watch',
    nameAr: 'ساعة جريس كرونوغراف فولاذية النخبة',
    priceAED: 4900,
    image: 'https://images.unsplash.com/photo-1522312346375-d1a52e2b99b3?auto=format&fit=crop&q=80&w=600',
    categoryEn: 'Luxury Perfumes & Watches',
    categoryAr: 'عطور وساعات فاخرة',
    descriptionEn: 'Precision automatic watch featuring textured deep black dial, sapphire crystal glass, and non-tarnish surgical steel links.',
    descriptionAr: 'ساعة يد أوتوماتيكية دقيقة بميناء أسود فاخر، زجاج من الكريستال الياقوتي المقاوم للخدش، وسلسلة فولاذية لا تتغير.',
    stockStatus: 'Low Stock',
    stockStatusAr: 'كمية محدودة',
    isPremium: true,
    stock: 5
  },
  {
    id: 'prod_5',
    nameEn: 'Saffiano Calfskin Leather Wallet',
    nameAr: 'محفظة جلد سافيانو الفاخرة',
    priceAED: 850,
    image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?auto=format&fit=crop&q=80&w=600',
    categoryEn: 'Premium Wallets, Sunglasses, & Belts',
    categoryAr: 'محافظ ونظارات وأحزمة راقية',
    descriptionEn: 'Crafted with premium Italian Saffiano leather, featuring multi-card slots, elegant structural lines, and gold monogram embossing.',
    descriptionAr: 'مصنوعة يدوياً من جلد السافيانو الإيطالي الفاخر، وتتميز بجيوب متعددة للبطاقات، وخطوط هيكلية أنيقة، ونقش ذهبي متميز.',
    stockStatus: 'In Stock',
    stockStatusAr: 'متوفر',
    isPremium: false,
    stock: 14
  },
  {
    id: 'prod_6',
    nameEn: 'Grace Aviator Gold-Plated Sunglasses',
    nameAr: 'نظارات جريس الطيار المطلية بالذهب',
    priceAED: 1100,
    image: 'https://images.unsplash.com/photo-1511499767150-a48a237f0083?auto=format&fit=crop&q=80&w=600',
    categoryEn: 'Premium Wallets, Sunglasses, & Belts',
    categoryAr: 'محافظ ونظارات وأحزمة راقية',
    descriptionEn: 'Ultralight polarized sunglasses featuring gold-plated titanium double bridges and premium UV400 protective charcoal lenses.',
    descriptionAr: 'نظارات شمسية مستقطبة خفيفة الوزن للغاية، تتميز بجسور مزدوجة من التيتانيوم المطلي بالذهب وعدسات واقية فحمية UV400.',
    stockStatus: 'In Stock',
    stockStatusAr: 'متوفر',
    isPremium: false,
    stock: 18
  }
];
